### ISSUE TITLE
Angular2 Example

### ISSUE THREAD

**Issue by pranaykothari** [pubnub/chat-engine-examples#8]
Hello Ian, 

Do you have an angular2 app reference? It will be a great help. Also,  I have browsed the document, but understading a group chat implementation with chat-engine is not clear. Any pointers to that?

Please see: I have also referred the channel topology section here: https://www.pubnub.com/docs/chat-engine/pubnub-channel-topology

Thanks for your help, 
Pranay.

**Comment by ianjennings** [comment]
There is an example work in progress here:
https://github.com/pubnub/chat-engine-examples/pull/12

**Comment by ianjennings** [comment]
All you need to do for group chat is have every user join a Chat with the same channel name. See this: https://www.pubnub.com/docs/chat-engine/chats
